project:
  type: book

book:
  title: "Developer Notes"
  author: "Kittipos"
  date: today
  repo-url: https://github.com/Lightbridge-KS/dev-notes
  site-url: https://dev-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Software Design
      chapters: 
        - "content/design/design_platform-abs-layer.qmd"
        - "content/design/design_dependency-injection.qmd"
        - "content/design/design_three_paradigms.qmd"
        - "content/design/design_dao.qmd"
        - "content/design/design_dao-RESTful-API.qmd"
        - "content/design/design_singleton_pattern.qmd"
    - part: WebService
      chapters: 
        - "content/backend/webservice-01-intro.qmd"
        - "content/backend/http-status-code.qmd"
        - "content/backend/webservice-02-python.ipynb"
    - part: Web URL
      chapters: 
        - "content/network/url-anatomy.qmd"
        - "content/backend/host-and-port.qmd"
    - part: Server
      chapters: 
        - "content/backend/ssh-overview.qmd"
        - "content/backend/ssh-intro.qmd"
        - "content/backend/ssh-vscode.qmd"
    - part: Client
      chapters: 
        - "content/storage/web-client-storage.qmd"
    - part: Crypto
      chapters: 
        - "content/crypto/https-jwt.qmd"
    - part: File system
      chapters: 
        - "content/fs/download-file.ipynb"
    - part: Firebase
      chapters: 
        - "content/firebase/firebase-flutter-hosting.qmd"
    - part: Versioning
      chapters: 
        - "content/version/semver-practical.qmd"
    - part: Linux
      chapters: 
        - "content/linux/linux-setup.qmd"
    - part: SSH
      chapters: 
        - "content/ssh/ssh-port-forwarding.qmd"
    - part: Git
      chapters: 
        - "content/git/git_rebase-vs-merge.qmd"
    - part: Network
      chapters: 
        - "content/network/gRPC.qmd"
        - "content/network/gRPC-vs-REST.qmd"
    - part: API
      chapters: 
        - "content/api/api-json-table-onerow.qmd"
    - part: Hardware
      chapters: 
        - "content/hardware/hardware_deeplearning-llm.qmd"
        - "content/hardware/hardware_ai-server-scaling.qmd"

bibliography: references.bib

format:
  html:
    theme:
      - cosmo


freeze: auto